version: '3.3'

services:
  db:
    image: mysql:5.7
    command: --init-file /data/application/setup.sql
    volumes:
      - ./setup.sql:/data/application/setup.sql
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - mindbook_net
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "32000:3306"

  app:
    build: .
    command: python app.py
    restart: always
    networks:
      - mindbook_net
    ports:
      - "5000:5000"
    depends_on:
      - db


networks:
  mindbook_net:

volumes:
  db_data:
